spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t7QDbpbsorQ2iUR5RVE
      secret-key: 7gMLtMgG3jOkAeDWzf6cUTOGu5QrxX
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: gulimall-zhonghui

  application:
    name: gulimall-third-party


server:
  port: 30000

